services:
  api:
    container_name: trading_engine_api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - .:/app
    ports:
      - "85:80"
    depends_on:
      - db
      - redis

  db:
    container_name: trading_engine_db
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-trading}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5435:5432"
    volumes:
      - trading_engine_pgdata:/var/lib/postgresql/data

  redis:
    container_name: trading_engine_redis
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - trading_engine_redisdata:/data

  celery_worker:
    container_name: trading_engine_celery_worker
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    command: celery -A app.celery_worker.celery_app worker --loglevel=info

  celery_beat:
    container_name: trading_engine_celery_beat
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - celery_worker
    command: celery -A app.celery_worker.celery_app beat --loglevel=info

volumes:
  trading_engine_pgdata:
  trading_engine_redisdata:
